#!/usr/bin/env bash

workdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

symlink() {
  local source="$1" destination="$2"
  [ ! -e "$destination" ] && ln -s "$PWD/$source" "$destination"
  [ ! -L "$destination" ] && echo "File at path "$destination" already exists" 1>&2
}

homelink() {
  symlink "$workdir/$1" "$HOME/$2"
}

# Update dotfiles submodules
echo "⏳ Updating submodules"
git submodule update --init

# Homebrew install
echo "⏳ Installing Homebrew"
brewpath=$(which brew)
[ ! -x "$brewpath" ] && \
  bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo "⏳ Installing Brewfile packages"
echo "⚠️  This may take some time"
brew bundle

# Install Oh-my-zsh
echo "⏳ Installing Oh-my-zsh"
export ZSH="$HOME/.zsh/.oh-my-zsh" KEEP_ZSHRC="yes"
[ ! -d $ZSH ] && \
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" ""

# Create directories
mkdir -p "$HOME/.config"
mkdir -p "$HOME/.gnupg"
mkdir -p "$HOME/.ssh"
mkdir -p "$HOME/Library/Application Support/Code/User"

# Link config to home directory
echo "⏳ Creating symlinks"
homelink "doom" ".config/"
homelink "gpg" ".gnupg"
homelink "gitconfig" ".gitconfig"
homelink "kitty" ".config"
homelink "nvim" ".config"
homelink "vim" ".vim"
homelink "vimrc" ".vimrc"
homelink "zsh" ".zsh"
homelink "zshrc" ".zshrc"
homelink "vscode/keybindings.json" "Library/Application Support/Code/User/keybindings.json"
homelink "vscode/settings.json" "Library/Application Support/Code/User/settings.json"

# Install doomemacs
echo "⏳ Installing doomemacs"
[ ! -d "$HOME/.config/emacs" ] && \
  git clone --depth 1 https://github.com/doomemacs/doomemacs "$HOME/.config/emacs"
# Run `doom sync`
"$HOME/.config/emacs/bin/doom" sync

# Install vim plugins
echo "⏳ Installing vim plugins"
vim +PlugInstall +qall

echo "✅ Done"
