#!/usr/bin/env bash
# This file is managed by adlawson/dotfiles
#
# Copyright (c) 2014 Andrew Lawson <http://adlawson.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

readonly IGNOREFILE=.rsyncignore
readonly DESTINATION=${DOTFILES_DIR:-$HOME}

help() {
    cat <<EOF

The install command rsyncs the dotfiles to the destination directory (~/) and
runs any necessary installation scripts.

Usage: install [options]

Available options:
  -h    Display this help message
  -s    Skip sourcing the updated .bash_profile
  -v    Skip installing the updated vim bundles

Environment variables:
  DOTFILES_DIR    The path to install the new files to (Defaults to $HOME)

EOF
    exit 1
}

install() {
    rsync --exclude-from "$IGNOREFILE" --exclude "$IGNOREFILE" -av --no-perms . "$DESTINATION"
}

install-vimrc() {
    vim +BundleInstall +qall
}

prompt-user() {
    read -n1 -p "This may overwrite existing files in $DESTINATION. Are you sure? (Y/n) "
    echo $REPLY
}

refresh-source() {
    source "$DESTINATION/.bash_profile"
}

main() {
    local source=true
    local vimrc=true

    while true; do
        case "$1" in
            -h) help; shift;;
            -s) source=false; shift;;
            -v) vimrc=false; shift;;
            *)  break;;
        esac
    done

    if [[ $(prompt-user) =~ ^[Yy]$ ]]; then
        echo

        install

        [[ $vimrc = true ]] && install-vimrc
        [[ $source = true ]] && refresh-source
    else
        echo
        echo "aborting..."
    fi
}

main "$@"
