# Homebrew Bundle
#
# ```
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# brew bundle
# ```

cask "1password"
cask "google-chrome"
cask "spotify"

brew "git"
brew "curl"
brew "fd"
brew "fzf"
brew "ripgrep"
brew "wget"
brew "zsh"

cask "docker"
brew "folderify"
cask "ghostty"
brew "go"
brew "neovim"
brew "nvm"
brew "oh-my-posh"
brew "vim"
cask "zed"
brew "uv"

cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-symbols-only-nerd-font"
